# Generated by Django 2.2.11 on 2020-03-31 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200330_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pstreet', models.CharField(max_length=70)),
                ('pcity', models.CharField(max_length=50)),
                ('pstreetrus', models.CharField(max_length=70)),
                ('pcityrus', models.CharField(max_length=50)),
                ('pccode', models.IntegerField()),
                ('pzip', models.CharField(max_length=6)),
                ('pph', models.CharField(max_length=20)),
                ('cstreet', models.CharField(max_length=70)),
                ('ccity', models.CharField(max_length=50)),
                ('cstreetrus', models.CharField(max_length=70)),
                ('ccityrus', models.CharField(max_length=50)),
                ('cccode', models.IntegerField()),
                ('czip', models.CharField(max_length=6)),
                ('cph', models.CharField(max_length=20)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_ph', models.CharField(max_length=20)),
                ('relation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MajorGeneralInfo',
            fields=[
                ('majorid', models.AutoField(primary_key=True, serialize=False)),
                ('majorrus', models.CharField(max_length=50)),
                ('majoreng', models.CharField(max_length=50)),
                ('majorkyr', models.CharField(max_length=50)),
                ('licence', models.CharField(max_length=20)),
                ('year_of_educ', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGeneralInfo',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('sex', models.BooleanField(default=False)),
                ('birth_date', models.DateField()),
                ('ncode', models.IntegerField()),
                ('ccode', models.IntegerField()),
                ('army_service', models.BooleanField(default=False)),
                ('army_standing', models.IntegerField()),
                ('rtoefl', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studgroup', models.CharField(max_length=3)),
                ('yeargroup', models.IntegerField()),
                ('incommingyear', models.IntegerField()),
                ('semestr', models.IntegerField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentGeneralInfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentGeneralInfo'),
        ),
    ]
